work_dir: ./work_dir/ntu120/xsub/baseline_ctrgcn_interaction_biBetaInit0_gama

# feeder
feeder: feeders.feeder_ntu.Feeder
num_worker: 1 ############################### 32
train_feeder_args:
  data_path: C:/Users/nkliu/Documents/paper/UnderReview/ICCV2023/interaction/ntu120/NTU120_CSub.npz
  split: train
  debug: False
  random_change: 0.9
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: False

test_feeder_args:
  data_path: C:/Users/nkliu/Documents/paper/UnderReview/ICCV2023/interaction/ntu120/NTU120_CSub.npz
  split: test
  window_size: 64
  p_interval: [0.95]
  vel: False
  bone: False
  debug: False

# model
model: model.baseline_ctrgcn_interaction_biBetaInit0_gama.Model
model_args:
  num_class: 26 #########################
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0004
base_lr: 0.1
lr_decay_rate: 0.1
step: [35, 55]
warm_up_epoch: 5

# training
device: [0] ######################### 0 1 2 3
batch_size: 3 ################### 64
test_batch_size: 1 ################# 64
num_epoch: 65
nesterov: True
